### PR TITLE
Add endpoint to get list of suppliers and fix logging issue

### LINKED ISSUE #27: Adding an item/supplier with zero data
When adding an item with all fields empty, the backend responds with 400 error. But also adds the item to the database, with empty data.

Like this; `{"name":"","location":"","min":0,"max":0,"current":0,"supplier":null,"link":""}`

### PR DESCRIPTION
**Pull request by WALLE-AXIOM**
fixes #27

### CODE REVIEW

File: backend/src/supplier.rs [hunk 1]
```diff
@@ -17,6 +17,12 @@ struct SupplierGetResponse {
     updated: i64,
 }
 
+#[derive(Debug, Serialize, Deserialize)]
+struct SupplierListGetResponse {
```
Comment (TXTstyle) [inline backend/src/supplier.rs:21]: Add ts type for this later

**Review by TXTstyle — APPROVED** [review]
LGTM
